### ISSUE TITLE
Getting error in webhook call.

### ISSUE THREAD

**Issue by hemratna** [pascalbaljetmedia/laravel-paddle#1]
Thanks a lot for the amazing package.

While making a webhook call from the Paddle webhook simulator, I am getting below error.

```error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure```

I configure the server with Laravel Forge.

Is there any steps I missing regarding the configuration.

**Comment by hemratna** [comment]
Below you'll also find configurations SSL for each server:

### nginx server (Forge)
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers EECDH+AESGCM:EDH+AESGCM;
ssl_prefer_server_ciphers on;

### Apache server:
SSLProtocol -all +TLSv1.3 +TLSv1.2;
SSLCipherSuite EECDH+AESGCM:EDH+AESGCM;
SSLHonorCipherOrder On;

### Lighttpd server:
ssl.openssl.ssl-conf-cmd = ("Protocol" => "-TLSv1.1, -TLSv1, -SSLv3") # v1.4.48 or up ssl.ec-curve = "secp384r1";
ssl.cipher-list = "EECDH+AESGCM:EDH+AESGCM";
ssl.honor-cipher-order = "enable";

**Comment by pascalbaljet** [comment]
These settings fixed the problem?

**Comment by hemratna** [comment]
@pascalbaljet Yes, Fixed in my case.
