### ISSUE TITLE
SSLv3 error on webhook for Paddle

### ISSUE THREAD

**Issue by petericebear** [pascalbaljetmedia/laravel-paddle#11]
Hi,

On a Laravel forge spinned up server I am trying to use the package but I get this error:
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

This is with the Webhook Simulator tester.

Any ideas how to get it to work?

**Comment by schollf** [comment]
This is a configuration error on your webserver. 
If you are using nginx change the SSL protocols to:

`ssl_protocols TLSv1.2 TLSv1.3;ssl_ciphers EECDH+AESGCM:EDH+AESGCM;ssl_prefer_server_ciphers on;`

**Comment by pascalbaljet** [comment]
There seems to be an issue with webhooks calls on Forge servers with the default SSL configuration. See also: https://github.com/pascalbaljetmedia/laravel-paddle/issues/1

**Comment by petericebear** [comment]
Thanks! Got it working with that.
