### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by joostvanhoof** [pascalbaljetmedia/laravel-paddle#12]
I'm quite lost regarding where exactly this issue occurs, so please excuse me if it turns out that it has nothing to do with this package.

When I test my webhook in the Paddle dashboard, I get `error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`. First, I thought that Paddle was connecting over SSLv3 but that seems highly unlikely as I've done some searching and it seems this is ancient and not recommended encryption.

On my nginx server I have (this might be relevant to the issue):
```
ssl_protocols TLSv1.2;
ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
ssl_prefer_server_ciphers on;
ssl_dhparam /etc/nginx/dhparams.pem;
```

The reason that I'm posting this issue here is that WebhookController has
```
$verified = openssl_verify(
  serialize($data),
  base64_decode($encodedSignature),
  openssl_get_publickey(config('paddle.public_key')),
  OPENSSL_ALGO_SHA1
);
```

Judging from the response that I get in the Paddle dashboard I still think it's on their end but I wanted to double check if the issue could come from the code above, or that maybe you ran into this issue as well while working on this package.

I have set my `public_key` in my ENV file and run `config:cache` on deployment.

**Comment by schollf** [comment]
Check #11 - that should solve it.

**Comment by joostvanhoof** [comment]
That solved it, thanks for the quick reply!
