### ISSUE TITLE
wrong API endpoint for getOrderDetails method

### ISSUE THREAD

**Issue by dimitribocquet** [pascalbaljetmedia/laravel-paddle#4]
When we call `getOrderDetails` method, it looks like the endpoint called is https://vendors.paddle.com/api/1.0/order, but it should be https://checkout.paddle.com/api/1.0/order instead.

With the first one, the method always returns a 404 error.

**Comment by pascalbaljet** [comment]
Fixed in v1.1.0, thanks for sharing!

**Comment by alzaabi98** [comment]
@dimitribocquet 

how to access this method "getOrderDetails "  ? I am looking for a way to find out subscription details like next payments, status directly from paddle

**Comment by dimitribocquet** [comment]
@alzaabi98 

`Paddle::checkout()->getOrderDetails();`

You can see some examples in the readme.
