### ISSUE TITLE
Paddle's Product Fulfillment webhook will return a 500 Error because there's no 'alert_name'

### ISSUE THREAD

**Issue by zoltanszogyenyi** [pascalbaljetmedia/laravel-paddle#8]
If you select webhook as a fulfillment for a product on Paddle, this will be used: https://developer.paddle.com/webhook-reference/product-fulfillment/fulfillment-webhook

As there is no "alert_name" set with this webhook, the library will have a 500 error. This is where the code breaks:

Event.php:

```
public static function fire(array $data)
    {
        $event = Str::studly($data['alert_name']);

        $eventClass = __NAMESPACE__ . '\\' . $event;

        event(new $eventClass($data));
    }
```

**Comment by pascalbaljet** [comment]
I've just tagged `v1.1.2`, which has a new `GenericWebhook` event. This event gets fired when the `alert_name` is missing. It also brings support for accessing the request:

```php
<?php

namespace App\Listeners;

use ProtoneMedia\LaravelPaddle\Events\GenericWebhook;

class HandleProductFulfillment
{
    public function handle(GenericWebhook $event)
    {
        $webhookData = $event->all();
        $request = $event->getRequest();
    }
}
```
